# 生产环境配置（GitHub 直接集成）
backend:
  name: github
  repo: YAMY1234/yamy-knowledge  # 替换为你的 GitHub 仓库
  branch: main
  # GitHub OAuth App Client ID
  client_id: "Ov23lisJIWDlWIG2mY4u"
  # 使用自定义认证端点
  base_url: https://yamy-knowledge.vercel.app
  auth_endpoint: admin/auth.html
  # 使用 implicit 模式，在主窗口中认证
  auth_type: implicit
  # 不使用弹窗
  auth_scope: repo

# 本地开发配置
# backend:
#   name: git-gateway
#   branch: main

local_backend: false  # 生产环境时设置为 false

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "llm-basics"
    label: "LLM 基础"
    folder: "docs/llm-basics"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string", required: true }
      - { label: "内容", name: "body", widget: "markdown", required: true }

  - name: "llm-advanced"
    label: "LLM 进阶"
    folder: "docs/llm-advanced"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string", required: true }
      - { label: "内容", name: "body", widget: "markdown", required: true }

  - name: "llm-infra"
    label: "LLM 基础设施"
    folder: "docs/llm-infra"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string", required: true }
      - { label: "内容", name: "body", widget: "markdown", required: true }

  - name: "blog"
    label: "博客文章"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string", required: true }
      - { label: "作者", name: "authors", widget: "list", allow_add: true, required: false }
      - { label: "标签", name: "tags", widget: "list", allow_add: true, required: false }
      - { label: "内容", name: "body", widget: "markdown", required: true } 