# 生产环境配置（GitHub 直接集成）
backend:
  name: github
  repo: YAMY1234/yamy-knowledge  # 替换为你的 GitHub 仓库
  branch: main
  # 强制使用 GitHub 直接认证，不通过 Netlify
  auth_type: implicit
  # 设置基础URL避免跳转到 Netlify
  base_url: https://yamy-knowledge.vercel.app
  # 明确指定不使用 Netlify 服务
  site_domain: yamy-knowledge.vercel.app
  # 如果创建了 GitHub OAuth App，请在这里填入 Client ID
  # client_id: "你的GitHub OAuth App Client ID"

# 本地开发配置
# backend:
#   name: git-gateway
#   branch: main

local_backend: false  # 生产环境时设置为 false

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "llm-basics"
    label: "LLM 基础"
    folder: "docs/llm-basics"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "内容", name: "body", widget: "markdown", required: true }

  - name: "llm-advanced"
    label: "LLM 进阶"
    folder: "docs/llm-advanced"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "内容", name: "body", widget: "markdown", required: true }

  - name: "llm-infra"
    label: "LLM 基础设施"
    folder: "docs/llm-infra"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "内容", name: "body", widget: "markdown", required: true }

  - name: "blog"
    label: "博客文章"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string", required: true }
      - { label: "作者", name: "authors", widget: "list", allow_add: true, required: false }
      - { label: "标签", name: "tags", widget: "list", allow_add: true, required: false }
      - { label: "内容", name: "body", widget: "markdown", required: true } 